app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'indx', 'uses' => 'WelcomeController@index']);
Route::get('/locale/{lang}', 'WelcomeController@changeLocale');

Route::post('/admin/password', '\App\Http\Controllers\Admin\AdminController@changePassword');

Route::get('/admin/sitemap', '\App\Http\Controllers\Admin\AdminController@sitemapGen');

Route::get('admin/settings/all', '\App\Http\Controllers\Admin\AdminSettingController@all');
Route::resource('admin/settings', '\App\Http\Controllers\Admin\AdminSettingController');
Route::get('admin/settings/del/{id}', '\App\Http\Controllers\Admin\AdminSettingController@del');

Route::get('admin/queues/all', '\App\Http\Controllers\Admin\AdminQueueController@all');
Route::resource('admin/queues', '\App\Http\Controllers\Admin\AdminQueueController');
Route::get('admin/queues/del/{id}', '\App\Http\Controllers\Admin\AdminQueueController@del');

Route::get('admin/questions/all', 'Admin\AdminQuestionController@all');
Route::post('admin/questions/change_visible_many', 'Admin\AdminQuestionController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/questions/filter', ['as' => 'questionFilter', 'uses' => 'Admin\AdminQuestionController@filter']);
Route::resource('admin/questions', 'Admin\AdminQuestionController');
Route::get('admin/questions/del/{id}', 'Admin\AdminQuestionController@del');
Route::post('admin/questions/del_many', 'Admin\AdminQuestionController@delMany');

Route::get('admin/answers/all', 'Admin\AdminAnswerController@all');
Route::post('admin/answers/change_visible_many', 'Admin\AdminAnswerController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/answers/filter', ['as' => 'answerFilter', 'uses' => 'Admin\AdminAnswerController@filter']);
Route::resource('admin/answers', 'Admin\AdminAnswerController');
Route::get('admin/answers/del/{id}', 'Admin\AdminAnswerController@del');
Route::post('admin/answers/del_many', 'Admin\AdminAnswerController@delMany');

Route::get('admin/members/all', 'Admin\AdminMemberController@all');
Route::post('admin/members/change_visible_many', 'Admin\AdminMemberController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/members/filter', ['as' => 'memberFilter', 'uses' => 'Admin\AdminMemberController@filter']);
Route::resource('admin/members', 'Admin\AdminMemberController');
Route::get('admin/members/del/{id}', 'Admin\AdminMemberController@del');
Route::post('admin/members/del_many', 'Admin\AdminMemberController@delMany');

Route::get('admin/ratings/all', 'Admin\AdminRatingController@all');
Route::post('admin/ratings/change_visible_many', 'Admin\AdminRatingController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/ratings/filter', ['as' => 'ratingFilter', 'uses' => 'Admin\AdminRatingController@filter']);
Route::resource('admin/ratings', 'Admin\AdminRatingController');
Route::get('admin/ratings/del/{id}', 'Admin\AdminRatingController@del');
Route::post('admin/ratings/del_many', 'Admin\AdminRatingController@delMany');

Route::post('answers/more', 'AnswerController@more');

Route::post('rating', 'RatingController@ratingChange');

Route::get('/question/{questionSlug}', 'QuestionController@oneQuestion');
Route::post('/question-publish', 'QuestionController@publish');

Route::get('/answer/{answerSlug}', 'AnswerController@oneAnswer');
Route::post('/answer-publish', 'AnswerController@publish');

/***************API***************************/
Route::get('/api/start/{page}', ['as' => 'api-indx', 'uses' => 'WelcomeController@indexApi']);
Route::get('/api/answers/{id}/{page}', ['as' => 'api-answ', 'uses' => 'AnswerController@showForApi']);
Route::get('/api/new', ['as' => 'api-new', 'uses' => 'WelcomeController@checkNewsApi']);

app/Models/Rating.php
<?php namespace App\Models;

 /**
 * This is the Question Rating model. 
 * It allow us to interact with the 'settings' table 
 * 
 * @package Models
 * @author Den
 */
use Illuminate\Database\Eloquent\Model;

class Rating extends Model {

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'ratings';

  /**
   * The attributes that are mass not assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = [];
  
  /**
   * Defines the belongsToMany/belongsToMany (many to many) relationship between Rating and Member models
   *
   * @return mixed
   */
  public function members() {
    return $this->belongsToMany('App\Models\Member', 'members_ratings', 'member_id', 'rating_id');
  }

 
}

app/Http/Controllers/RatingController.php
<?php namespace App\Http\Controllers;

use App\Repositories\RatingRepository;
use Illuminate\Http\Request;

/**
 * Rating Controller
 * 
 * @package Http
 * @subpackage Controllers
 */
class RatingController extends Controller {

    /**
     * Rating Repository
     *
     * @var App\Repositories\RatingRepository
     */
    protected $rating;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(RatingRepository $rating) {
        $this->middleware('checkMember');
        $this->middleware('setLoc');
        $this->rating = $rating;
    }

    /**
     * Change Rating.
     *
     * @return Response
     */
    public function ratingChange(Request $request) {
        return $this->rating->ratingChange($request);
    }

}

resources/views/admin/ratings/create.blade.php
@extends('part_app')

@section('content')

<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Rating </div>

            <div class="panel-body">

                {!! Form::model(new App\Models\Rating, ['route' => ['admin.ratings.store'],'role'=>'form','class'=>'block small center login','style'=>'height:80%']) !!}
                @include('admin/ratings/_partials/form', ['submit_text' => 'New Rating'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/ratings/del.blade.php
@extends('part_app')

@section('content')
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete rating with id "{{$id}}"</h4>
      </div>
      <div class="modal-body">
        <p>Are you shure?</p>
      </div>
      <div class="modal-footer">
          {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.ratings.destroy', $id))) !!}
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
         <input class="form-control" name="page" type="hidden" value="<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" id="page">
        
         {!! Form::submit('Yes', array('class' => 'btn btn-primary')) !!}
                     
             {!! Form::close() !!}
      </div>
@stop

resources/views/admin/ratings/edit.blade.php
@extends('part_app')

@section('content')
<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">Edit Rating "{{ $rating->title }}" with ID "{{ $rating->id }}" </div>

            <div class="panel-body">

                {!! Form::model($rating, ['method' => 'PATCH', 'route' => ['admin.ratings.update', $rating->id],'role'=>'form','class'=>'block small center login','style'=>'height:80%', 'files'=>true]) !!}
                @include('admin/ratings/_partials/form', ['submit_text' => 'Edit Rating'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/ratings/index.blade.php
<div class="container">
    
    @if (Session::has('message'))
            <div class="flash alert-info">
                <p>{!! Session::get('message') !!}</p>
            </div>
    @endif
   @if (Session::has('error'))
            <div class="flash alert-danger">
                <p>{!! Session::get('error') !!}</p>
            </div>
   @endif        
            @if ($errors->any())
            <div class='flash alert-danger'>
                @foreach ( $errors->all() as $error )
                <p>{{ $error }}</p>
                @endforeach
            </div>
            @endif
  
	<div class="col-md-10 col-md-offset">
   <div class="panel panel-default">
				<div class="panel-heading">Administration Panel - Рейтиги</div>

				<div class="panel-body">
            
            <a class="delete_selected btn btn-danger disabled">Delete Selected</a>

            <div class="col-md-13 col-md-offset" style="float:right;">
            {!! Form::open(array('class' => 'form-inline', 'method' => 'POST', 'url' => '/admin/ratings/filter')) !!}

             <input class="form-control" name="limit" type="text" value="{{isset($limit) ? $limit : '10'}}" placeholder="макс. кол-во (шт.)" style="width:70px">
             <select class="form-control memberus" name="memberSel" style="width:200px">
                                         <option value="">Любой Юзер</option>
                                         @foreach ($members as $member)
                                         <option  value="{{$member->id}}"  @if(isset($memberSel)&&($member->id == $memberSel)) selected @endif>
                                                  IP: {{$member->ip}}; ID: {{$member->id}}
                                         </option>
                                         @endforeach
             </select>
            
             <input type="checkbox" name="sort" @if(isset($sort)&&($sort == 'desc')) checked @endif />desc(set)/asc
             {!! Form::submit('apply', array('class' => 'btn btn-info')) !!}
             {!! Form::close() !!}
             </div>
            {!! link_to_route('admin.ratings.create', 'Create New Rating', array() ,array('class' => '', 'data-toggle'=>'modal', 'data-target'=>'#createRating') ) !!}<br><br>
             <div class="table-responsive"> 
                 <table class="table table-bordered" data-search="true" data-url="">
                     <thead>
                         <tr>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAll">
                                  Select All
                              </div>
                             </th>
                             <th data-sortable="true">ID</th>
                            
                             <th>R+</th>
                             <th>R-</th>
                             <th>R sum</th>
                             
                             <th>Operations</th>
                         </tr>
                     </thead>
                     <tbody>
                         @foreach ($ratings as $rating)
                         <tr>
                              <td>
                                 <div>
                                     <input type="checkbox" class="rating-delete" id="id{{$rating->id}}" data-id="{{$rating->id}}">
                                 </div>
                             </td>
                             <td class="delete_toggler">{{$rating->id}}</td>

                             <td>{{$rating->rating_plus}}</td>
                             <td>{{$rating->rating_minus}}</td>
                             <td>{{$rating->summary}}</td>  
                               <td>
                              <a href="/admin/ratings/{{$rating->id}}/edit?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-info" data-toggle="modal" data-target="#editRating{{$rating->id}}">Edit</a>
                                 <div id="editRating{{$rating->id}}" class="modal fade" >
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                                 <a href="/admin/ratings/del/{{$rating->id}}?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-danger" data-toggle="modal" data-target="#delRating{{$rating->id}}">Delete</a>

                                 <div id="delRating{{$rating->id}}"  class="modal fade">
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                             </td>
                         </tr>
                         @endforeach
                     </tbody>
                 </table>

                
                 
                  @if ($ratings && (!isset($all)))

                    @if (!isset($limit))
                    {!! $ratings->appends(Input::except('page'))->render() !!}
                    <ul class="pagination">
                    <li><a href="/admin/ratings/all">All</a></li>
                    </ul>
                    @else
                    <ul class="pagination">
                    <li><a href="/admin/ratings">1</a></li>
                    </ul>
                    @endif

                 @else
                 <ul class="pagination">
                 <li><a href="/admin/ratings">1</a></li>
                 </ul>
                 @endif
                 <input type="hidden" id="pageNumb" value="<?php if (isset($_GET['page'])) echo $_GET['page']; else echo '1'; ?>">
                 
             </div>
        </div>
        
    </div> 
</div>
    
</div>    

@include('admin._partials.modal', ['elementId' => 'createRating']) 

@include('admin._partials.del-modal', ['url' => '/admin/ratings/del_many'])

@include('admin.js')