app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'indx', 'uses' => 'WelcomeController@index']);
Route::get('/locale/{lang}', 'WelcomeController@changeLocale');

Route::post('/admin/password', '\App\Http\Controllers\Admin\AdminController@changePassword');

Route::get('/admin/sitemap', '\App\Http\Controllers\Admin\AdminController@sitemapGen');

Route::get('admin/settings/all', '\App\Http\Controllers\Admin\AdminSettingController@all');
Route::resource('admin/settings', '\App\Http\Controllers\Admin\AdminSettingController');
Route::get('admin/settings/del/{id}', '\App\Http\Controllers\Admin\AdminSettingController@del');

Route::get('admin/queues/all', '\App\Http\Controllers\Admin\AdminQueueController@all');
Route::resource('admin/queues', '\App\Http\Controllers\Admin\AdminQueueController');
Route::get('admin/queues/del/{id}', '\App\Http\Controllers\Admin\AdminQueueController@del');

Route::get('admin/questions/all', 'Admin\AdminQuestionController@all');
Route::post('admin/questions/change_visible_many', 'Admin\AdminQuestionController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/questions/filter', ['as' => 'questionFilter', 'uses' => 'Admin\AdminQuestionController@filter']);
Route::resource('admin/questions', 'Admin\AdminQuestionController');
Route::get('admin/questions/del/{id}', 'Admin\AdminQuestionController@del');
Route::post('admin/questions/del_many', 'Admin\AdminQuestionController@delMany');

Route::get('admin/answers/all', 'Admin\AdminAnswerController@all');
Route::post('admin/answers/change_visible_many', 'Admin\AdminAnswerController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/answers/filter', ['as' => 'answerFilter', 'uses' => 'Admin\AdminAnswerController@filter']);
Route::resource('admin/answers', 'Admin\AdminAnswerController');
Route::get('admin/answers/del/{id}', 'Admin\AdminAnswerController@del');
Route::post('admin/answers/del_many', 'Admin\AdminAnswerController@delMany');

Route::get('admin/members/all', 'Admin\AdminMemberController@all');
Route::post('admin/members/change_visible_many', 'Admin\AdminMemberController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/members/filter', ['as' => 'memberFilter', 'uses' => 'Admin\AdminMemberController@filter']);
Route::resource('admin/members', 'Admin\AdminMemberController');
Route::get('admin/members/del/{id}', 'Admin\AdminMemberController@del');
Route::post('admin/members/del_many', 'Admin\AdminMemberController@delMany');

Route::get('admin/ratings/all', 'Admin\AdminRatingController@all');
Route::post('admin/ratings/change_visible_many', 'Admin\AdminRatingController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/ratings/filter', ['as' => 'ratingFilter', 'uses' => 'Admin\AdminRatingController@filter']);
Route::resource('admin/ratings', 'Admin\AdminRatingController');
Route::get('admin/ratings/del/{id}', 'Admin\AdminRatingController@del');
Route::post('admin/ratings/del_many', 'Admin\AdminRatingController@delMany');

Route::post('answers/more', 'AnswerController@more');

Route::post('rating', 'RatingController@ratingChange');

Route::get('/question/{questionSlug}', 'QuestionController@oneQuestion');
Route::post('/question-publish', 'QuestionController@publish');

Route::get('/answer/{answerSlug}', 'AnswerController@oneAnswer');
Route::post('/answer-publish', 'AnswerController@publish');

/***************API***************************/
Route::get('/api/start/{page}', ['as' => 'api-indx', 'uses' => 'WelcomeController@indexApi']);
Route::get('/api/answers/{id}/{page}', ['as' => 'api-answ', 'uses' => 'AnswerController@showForApi']);
Route::get('/api/new', ['as' => 'api-new', 'uses' => 'WelcomeController@checkNewsApi']);

app/Models/Answer.php
<?php namespace App\Models;

 /**
 * This is the Question model. 
 * It allow us to interact with the 'questions' table 
 * 
 * @package Models
 * @author Den
 */
use Illuminate\Database\Eloquent\Model;

class Answer extends Model {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'answers';

    /**
     * The attributes that are mass not assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * Defines the belongsTo/hasMany (one to many) relationship between Answer and Member models
     *
     * @return mixed
     */
    public function member() {
        return $this->belongsTo('App\Models\Member');
    }

    /**
     * Defines the belongsTo/hasMany (one to many) relationship between Answer and Question models
     *
     * @return mixed
     */
    public function question() {
        return $this->belongsTo('App\Models\Question');
    }

    /**
     * Defines the belongsTo/hasOne(one to one) relationship between Answer and Rating models
     *
     * @return mixed
     */
    public function rating() {
        return $this->belongsTo('App\Models\Rating');
    }

}

app/Http/Controllers/AnswerController.php
<?php namespace App\Http\Controllers;

use App\Repositories\AnswerRepository;
use Illuminate\Http\Request;

/**
 * Answer Controller
 * 
 * @package Http
 * @subpackage Controllers
 */
class AnswerController extends Controller {

    /**
     * Answer Repository
     *
     * @var App\Repositories\AnswerRepository
     */
    protected $answer;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(AnswerRepository $answer) {
        $this->middleware('checkMember');
        $this->middleware('setLoc');
        $this->answer = $answer;
    }

    /**
     * Show more answers.
     *
     * @return Response
     */
    public function more(Request $request) {
        return $this->answer->moreAnswers($request);
    }

    public function oneAnswer($answerSlug) {
        $data = $this->answer->getAnswerBySlug($answerSlug);
        return view('answer', $data);
    }

    public function publish(Request $request) {
        return $this->answer->publishAnswer($request);
    }

    public function showForApi($id, $page = 0) {

        $data = $this->answer->showForApi($id, $page);

        echo json_encode($data);
    }

}

resources/views/admin/answers/create.blade.php
@extends('part_app')

@section('content')

<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Answer </div>

            <div class="panel-body">

                {!! Form::model(new App\Models\Answer, ['route' => ['admin.answers.store'],'role'=>'form','class'=>'block small center login','style'=>'height:80%']) !!}
                @include('admin/answers/_partials/form', ['submit_text' => 'New Answer'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/answers/del.blade.php
@extends('part_app')

@section('content')
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete answer with id "{{$id}}"</h4>
      </div>
      <div class="modal-body">
        <p>Are you shure?</p>
      </div>
      <div class="modal-footer">
          {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.answers.destroy', $id))) !!}
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
         <input class="form-control" name="page" type="hidden" value="<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" id="page">
         <input class="form-control" name="memberSel" type="hidden" value="<?php if (isset($_GET['memberSel'])) echo $_GET['memberSel']; ?>" id="memberSel">
          <input class="form-control" name="questionSel" type="hidden" value="<?php if (isset($_GET['questionSel'])) echo $_GET['questionSel']; ?>" id="questionSel">
           <input class="form-control" name="ratingSel" type="hidden" value="<?php if (isset($_GET['ratingSel'])) echo $_GET['ratingSel']; ?>" id="ratingSel">
         {!! Form::submit('Yes', array('class' => 'btn btn-primary')) !!}
                     
             {!! Form::close() !!}
      </div>
@stop

resources/views/admin/answers/edit.blade.php
@extends('part_app')

@section('content')
<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">Edit Answer "{{ $answer->title }}" with ID "{{ $answer->id }}" </div>

            <div class="panel-body">

                {!! Form::model($answer, ['method' => 'PATCH', 'route' => ['admin.answers.update', $answer->id],'role'=>'form','class'=>'block small center login','style'=>'height:80%', 'files'=>true]) !!}
                @include('admin/answers/_partials/form', ['submit_text' => 'Edit Answer', 'members' => $members, 'questions' => $questions,'ratings' => $ratings])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/answers/index.blade.php
<div class="container">
    
    @if (Session::has('message'))
            <div class="flash alert-info">
                <p>{!! Session::get('message') !!}</p>
            </div>
    @endif
   @if (Session::has('error'))
            <div class="flash alert-danger">
                <p>{!! Session::get('error') !!}</p>
            </div>
   @endif        
            @if ($errors->any())
            <div class='flash alert-danger'>
                @foreach ( $errors->all() as $error )
                <p>{{ $error }}</p>
                @endforeach
            </div>
            @endif
  
	<div class="col-md-10 col-md-offset">
   <div class="panel panel-default">
				<div class="panel-heading">Administration Panel - Видео-Ответы</div>

				<div class="panel-body">
            
            <a class="delete_selected btn btn-danger disabled">Delete Selected</a>

            <div class="col-md-13 col-md-offset" style="float:right;">
            {!! Form::open(array('class' => 'form-inline', 'method' => 'POST', 'url' => '/admin/answers/filter')) !!}

             <input class="form-control" name="limit" type="text" value="{{isset($limit) ? $limit : '10'}}" placeholder="макс. кол-во (шт.)" style="width:70px">
             <select class="form-control memberus" name="memberSel" style="width:100px">
                                         <option value="">Юзер</option>
                                         @foreach ($members as $member)
                                         <option  value="{{$member->id}}"  @if(isset($memberSel)&&($member->id == $memberSel)) selected @endif>
                                                  IP: {{$member->ip}}; ID: {{$member->id}}
                                         </option>
                                         @endforeach
             </select>
             <select class="form-control questionus" name="questionSel" style="width:100px">
                                         <option value="">Вопрос</option>
                                         @foreach ($questions as $question)
                                         <option  value="{{$question->id}}"  @if(isset($questionSel)&&($question->id == $questionSel)) selected @endif>
                                                  ID: {{$question->id}}; TITLE: {{$question->title}}
                                         </option>
                                         @endforeach
             </select>
             <select class="form-control" name="ratingSel" type="text" style="width:100px" >
                    <option value="">Рейтинг</option>
                    @foreach ($ratings as $rating)
                    <option value="{{$rating->id}}" @if(isset($ratingSel)&&($rating->id == $ratingSel)) selected @endif>
                            ID: {{$rating->id}}
                    </option>
                    @endforeach
            </select>
             <input type="checkbox" name="sort" @if(isset($sort)&&($sort == 'desc')) checked @endif />desc(set)/asc
             {!! Form::submit('apply', array('class' => 'btn btn-info')) !!}
             {!! Form::close() !!}
             </div>
            {!! link_to_route('admin.answers.create', 'Create New Answer', array() ,array('class' => '', 'data-toggle'=>'modal', 'data-target'=>'#createAnswer') ) !!}<br><br>
             <div class="table-responsive"> 
                 <table class="table table-bordered" data-search="true" data-url="">
                     <thead>
                         <tr>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAll">
                                  Select All
                              </div>
                             </th>
                             <th data-sortable="true">ID</th>
                             <th>Question</th>
                             <th>Member</th>
                              <th>R.ID</th>
                             <th>Title</th>
                             <th>Description</th>
                             <th>Mob</th>
                             <th>Thumb</th>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAllVisible" data-url="answers"> Visible
                              </div>
                             </th>
                             <th>Operations</th>
                         </tr>
                     </thead>
                     <tbody>
                         @foreach ($answers as $answer)
                         <tr>
                              <td>
                                 <div>
                                     <input type="checkbox" class="answers-delete" id="id{{$answer->id}}" data-id="{{$answer->id}}">
                                 </div>
                             </td>
                             <td class="delete_toggler">{{$answer->id}}</td>
                             <td>{{$answer->question_id}}</td>
                             <td>{{$answer->member_id}}</td>
                             <td>{{$answer->rating_id}}</td>
                             <td>
                                <div data-toggle="tooltip" data-placement="bottom" title="{{$answer->title}}">
                                     {!!mb_strimwidth($answer->title, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$answer->description}}">
                                     {!!mb_strimwidth($answer->description, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <td>{{$answer->ext}}</td>
                               <td style="height:130px;width:130px"><img src="{{$answer->url_thumb}}" style="height:130px;width:130px"></td>
                               
                               <td>
                               <input type="checkbox" class="visible-change" data-url="answers" name="visible" @if($answer->visible==1) checked @endif data-id="{{$answer->id}}">
                               </td>
                               
                               <td>
                              <a href="/admin/answers/{{$answer->id}}/edit?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-info" data-toggle="modal" data-target="#editAnswer{{$answer->id}}">Edit</a>
                                 <div id="editAnswer{{$answer->id}}" class="modal fade" >
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                                 <a href="/admin/answers/del/{{$answer->id}}?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-danger" data-toggle="modal" data-target="#delAnswer{{$answer->id}}">Delete</a>

                                 <div id="delAnswer{{$answer->id}}"  class="modal fade">
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                             </td>
                         </tr>
                         @endforeach
                     </tbody>
                 </table>

                
                 
                  @if ($answers && (!isset($all)))

                    @if (!isset($limit))
                    {!! $answers->appends(Input::except('page'))->render() !!}
                    <ul class="pagination">
                    <li><a href="/admin/answers/all">All</a></li>
                    </ul>
                    @else
                    <ul class="pagination">
                    <li><a href="/admin/answers">1</a></li>
                    </ul>
                    @endif

                 @else
                 <ul class="pagination">
                 <li><a href="/admin/answers">1</a></li>
                 </ul>
                 @endif
                 <input type="hidden" id="pageNumb" value="<?php if (isset($_GET['page'])) echo $_GET['page']; else echo '1'; ?>">
                 
             </div>
        </div>
        
    </div> 
</div>
    
</div>    

@include('admin._partials.modal', ['elementId' => 'createAnswer']) 

@include('admin._partials.del-modal', ['url' => '/admin/answers/del_many'])

@include('admin.js')